Repository greenIy/greenly, pull requests merged in 2022-07, with the labels that each got.

#95 94 fix routes
  client/src/components/Frontpage/TheNavbar.vue
  client/src/components/Product/ProductCard.vue
  client/src/components/Profile/ProductCard.vue
  client/src/components/Supplier/Inventory.vue
  client/src/router/index.js
  client/src/views/ProductView.vue
  client/src/views/SupplierView.vue
  client/src/views/TransporterView.vue
Labels: bugfix

#102 Added Cypress tests, added data-cy anchors to necessary elements.
  client/src/components/Frontpage/TheNavbar.vue
  client/src/components/Login/LoginForm.vue
  client/src/components/Product/ProductCard.vue
  client/src/components/Profile/Profile.vue
  client/src/components/Profile/ProfileSecurity.vue
  client/src/components/Profile/ProfileWishlist.vue
  client/src/components/Register/RegisterConsumidor.vue
  client/src/components/Register/RegisterFornecedor.vue
  client/src/components/Register/RegisterPills.vue
  client/src/components/Register/RegisterTransportador.vue
  client/src/components/Supplier/Warehouses.vue
  client/src/components/Transporter/DistributionCenters.vue
  client/src/views/CartView.vue
  client/src/views/ProductView.vue
  client/src/views/ProductsView.vue
  client/src/views/SupplierView.vue
  client/src/views/TransporterView.vue
  server/package-lock.json
  server/package.json
  server/tests/unit/cypress.config.js
  server/tests/unit/cypress.env.json
  server/tests/unit/cypress/e2e/01-general/01-getProducts.cy.js
  server/tests/unit/cypress/e2e/01-general/02-login.cy.js
  server/tests/unit/cypress/e2e/02-registration/03-registerConsumer.cy.js
  server/tests/unit/cypress/e2e/02-registration/04-registerSupplier.cy.js
  server/tests/unit/cypress/e2e/02-registration/05-registerTransporter.cy.js
  server/tests/unit/cypress/e2e/03-wishlist/06-addProductToWishlist.cy.js
  server/tests/unit/cypress/e2e/03-wishlist/07-getWishlist.cy.js
  server/tests/unit/cypress/e2e/03-wishlist/08-clearWishlist.cy.js
  server/tests/unit/cypress/e2e/04-cart/09-addProductToCart.cy.js
  server/tests/unit/cypress/e2e/04-cart/10-getCart.cy.js
  server/tests/unit/cypress/e2e/04-cart/11-clearCart.cy.js
  server/tests/unit/cypress/e2e/05-supplier/12-supplier-orders.cy.js
  server/tests/unit/cypress/e2e/05-supplier/13-supplier-warehouses.cy.js
  server/tests/unit/cypress/e2e/05-supplier/14-supplier-supplies.cy.js
  server/tests/unit/cypress/e2e/06-transporter/15-transporter-orders.cy.js
  server/tests/unit/cypress/e2e/06-transporter/16-transporter-centers.cy.js
  server/tests/unit/cypress/e2e/06-transporter/17-transporter-vehicles.cy.js
  server/tests/unit/cypress/e2e/07-deletion/18-deleteSupplier.cy.js
  server/tests/unit/cypress/e2e/07-deletion/19-deleteTransporter.cy.js
  server/tests/unit/cypress/e2e/07-deletion/20-deleteConsumer.cy.js
  server/tests/unit/cypress/support/commands.js
  server/tests/unit/cypress/support/e2e.js
Labels: enhancement, bugfix

#104 Melhoramento da rota de estatísticas para administradores
  doc/api/rest_api.yaml
  server/lib/persistence.js
  server/package-lock.json
  server/package.json
Labels: documentation, enhancement

#105 Responsiveness Geral
  client/package-lock.json
  client/src/components/Cart/CartProductCard.vue
  client/src/components/Checkout/CartInfo.vue
  client/src/components/Frontpage/TheFooter.vue
  client/src/components/Frontpage/TheNavbar.vue
  client/src/components/Login/LoginForm.vue
  client/src/components/Product/CatalogPage/TheFilters.vue
  client/src/components/Product/CatalogPage/TheUtilityBar.vue
  client/src/components/Product/CompareProduct.vue
  client/src/components/Product/ProductCard.vue
  client/src/components/Profile/ProductCard.vue
  client/src/components/Profile/Profile.vue
  client/src/components/Profile/ProfileAddresses.vue
  client/src/components/Profile/ProfileOrders.vue
  client/src/components/Profile/ProfilePersonalInfo.vue
  client/src/components/Profile/ProfileSecurity.vue
  client/src/components/Profile/ProfileWishlist.vue
  client/src/components/Register/RegisterFornecedor.vue
  client/src/components/Supplier/EncomendasDashboard.vue
  client/src/components/Supplier/History.vue
  client/src/components/Supplier/Inventory.vue
  client/src/components/Supplier/Warehouses.vue
  client/src/components/Transporter/DistributionCenters.vue
  client/src/components/Transporter/EncomendasDashboard.vue
  client/src/components/Transporter/History.vue
  client/src/components/Transporter/Vehicles.vue
  client/src/views/AboutView.vue
  client/src/views/CartView.vue
  client/src/views/HomeView.vue
  client/src/views/PartnersTransportersView.vue
  client/src/views/ProductView.vue
  client/src/views/ProductsView.vue
  client/src/views/ProfileView.vue
  client/src/views/SupplierView.vue
  client/src/views/SuppliersView.vue
  client/src/views/TransporterView.vue
  server/lib/persistence.js
Labels: enhancement, bugfix

#106 99 finish warehouses
  client/package-lock.json
  client/src/components/Profile/Country-select.vue
  client/src/components/Profile/Profile.vue
  client/src/components/Profile/ProfileAddresses.vue
  client/src/components/Profile/ProfileStatistics.vue
  client/src/components/Supplier/Inventory.vue
  client/src/components/Supplier/Warehouses.vue
  client/src/components/Transporter/DistributionCenters.vue
  client/src/components/Transporter/Vehicles.vue
  client/src/router/index.js
  client/src/views/SupplierView.vue
  client/src/views/TransporterView.vue
Labels: enhancement, bugfix

#107 98 admin graphs
  client/package-lock.json
  client/package.json
  client/src/components/Administration/Chart.vue
  client/src/views/AdminView.vue
Labels: enhancement
